### ISSUE TITLE
Add Search to Desktop & Mobile

### ISSUE THREAD

**Issue by mrbrianbaker** [esmyth01/cossar#29]
Search to top of sidebar for Desktop and in nav-bar for mobile

**Comment by nshakir** [comment]
Did we find any plugins for this?
Here's a few cool ones just in case

http://52.88.123.0/wp-admin/plugin-install.php?tab=plugin-information&plugin=daves-wordpress-live-search&TB_iframe=true&width=772&height=662

http://52.88.123.0/wp-admin/plugin-install.php?tab=plugin-information&plugin=curated-search&TB_iframe=true&width=772&height=662

http://52.88.123.0/wp-admin/plugin-install.php?tab=plugin-information&plugin=custom-search-plugin&TB_iframe=true&width=772&height=662

**Comment by mrbrianbaker** [comment]
Added get_search_form to front-page sidebar and added a function to functions.php to add it in the mobile  nav
Styled accordingly
