### ISSUE TITLE
Remove Page Titles since we now have Header Text

### ISSUE THREAD

**Issue by nshakir** [esmyth01/cossar#50]
It appears redundant since we see the page title in the header text, then the breadcrumbs and then under displays the page title again.

**Comment by nshakir** [comment]
I attempted to remove the page title.  however when its removed it looks a little weird.  Let me know what you think.  I won't commit this for now.

**Comment by mrbrianbaker** [comment]
Ok I took off the page title from the header text, and made it display the top-level parent page name instead.
