### ISSUE TITLE
Dynamic Slider Images/Headlines/Text

### ISSUE THREAD

**Issue by mrbrianbaker** [esmyth01/cossar#51]
To match visual specs; pulling featured image, headline, and excerpt into homepage banner slider

/\* slider text box */

.slider-box {
 color: #fff;
 position: absolute;
 bottom: 0;
 right: 0;
 width: 50%;
 box-sizing: border-box;
 padding: 1em;
 background-color: rgba(0,0,0,.75);
}

.slider-box h3 {
 font-family: Oswald Medium;
 font-size: 1.375em; /_22px_/
}

.slider-excerpt {
 width: 65%;
 padding-top:1em;
 font-family: Source Sans Pro;
 font-size: .875em; /_14px_/
}

**Comment by mrbrianbaker** [comment]
Evan - wondering if we can get this figured out before Tuesday? If not, maybe we can fake it and get it finished by Friday. I can try looking into it if you want, just let me know

**Comment by esmyth01** [comment]
Well, The flexslider is already dynamic, and all you have to do to change it is replace the images with new ones. Now the excerpts I already looked into, but apparently you need to pay money to use that feature on the slider. We could try to hack it, and create our own though.

**Comment by nshakir** [comment]
Pretty sure I was looking for sliders and saw another one that was free.  Not too sure if you would want to try it all over again.  I can send the link when I get home.

**Comment by mrbrianbaker** [comment]
I like this one, design 2 (since it's really close to our visual):
https://wordpress.org/plugins/wp-responsive-recent-post-slider/

I was also able to tweak the css when I inspected it, which I hope we could do with the installed plugin as well. I'll test it on my local to see if it can work how we need it to!

**Comment by mrbrianbaker** [comment]
Ok I'm 99% sure I got this!! :)

I'm going to work it out on my local, and then commit everything for the new slider!

**Comment by mrbrianbaker** [comment]
Got it! I will email you guys the zipped plugin to install locally, and will upload the plugin to our WP! I had to break into the css and make some edits inside the plugin, so it is not exactly like the one in WP. Might be a good idea to recommend no updates, in case updating would negate the changes we needed for it to look good.
