### ISSUE TITLE
MOBILE: Set width on single blog post wider

### ISSUE THREAD

**Issue by nshakir** [esmyth01/cossar#52]
Single post are too thin for blog, comment also need tweaking

**Comment by esmyth01** [comment]
Did quite a few things, everything should be dynamic now. Also I made some custom functions to display excerpts and content with a character limit, followed by read more. There seems to be some weird search thing showing up on page.php though, any thoughts? 

```
On Monday, December 14, 2015 8:52 PM, Nectar Shakir <notifications@github.com> wrote:
```

 Single post are too thin for blog, comment also need tweaking—

**Comment by mrbrianbaker** [comment]
Yeah I'll get that. It looked shifted to the left so I made some adjustments that worked on my local and with firebug. Probably something in there. I'm making some other notes too; I'll do a couple tweaks in the morning before work!

**Comment by mrbrianbaker** [comment]
Single page post is now at 95%, 0 auto
Comment text box at max-width 100%
Added wp-caption max-width 100% so images on single page posts are responsive and don't overflow the div/page
